spring:
  application:
    name: gatewayService
  profiles:
    active: dev
  config:
    import: optional:configserver:http://miracle:1234@3.36.100.180:60010
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

miracle:
  passwordChecker: ef5008azffhhfcc3371a7d4zzcv23f!6f4bb432c8e3b3a16835392f540b28fasdmlbirqe767366b4pyurib681f385284cd8deqwer==qadafq

cloud:
  aws:
    s3:
      bucket: miracle-job-a
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${accessKey}
      secretKey: ${secretKey}



