server:
  port: 60000

spring:
  devtools:
    livereload:
      # 정적 리소스 변화가 있을 때 반영
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    # 타임리프 참조 경로
    prefix: classpath:/templates/
    suffix: .html

    # 캐시 저장 여부
    cache: false

    # 디렉토리에 파일이 있는지 체크, 없으면 에러발생 유도
    check-template-location: true

  mail:
    host: smtp.naver.com
    port: 587
    username: junn811@naver.com
    password: S9X3DFPFH9T7
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

